services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - ./prometheus/.env
    labels:
      - "net.unraid.docker.webui=http://[IP]:[PORT:9090]"
    ports:
      - '9090:9090'
    volumes:
      - /mnt/user/Docker_Mounts/unpoller-unifi/prometheus/config:/etc/prometheus
      - /mnt/user/Docker_Mounts/unpoller-unifi/prometheus/data:/prometheus
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - ./grafana/.env
    labels:
      - "net.unraid.docker.webui=http://[IP]:[PORT:3001]"
    ports:
      - '3001:3000'
    volumes:
      - /mnt/user/Docker_Mounts/unpoller-unifi/grafana/data:/var/lib/grafana
      - /mnt/user/Docker_Mounts/unpoller-unifi/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /mnt/user/Docker_Mounts/unpoller-unifi/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    restart: unless-stopped
    container_name: unpoller
    env_file:
      - ./unpoller/.env
    labels:
      - "net.unraid.docker.webui=http://[IP]:[PORT:9130]"
    ports:
      - '9130:9130'

