modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [ 200, 204, 301, 302, 307, 308, 401, 403 ]
      headers:
        User-Agent: "Mozilla/5.0 (compatible; Unifi-Poller-Blackbox/1.0)"
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false

  icmp:
    prober: icmp
    timeout: 5s
    # you can add additional settings like "preferred_ip_protocol" if needed

  dns:
    prober: dns
    timeout: 5s
